name: 'Run CI jobs'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: '${{ matrix.runner }}'
    strategy:
      max-parallel: 4
      matrix:
        runner:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
          - 'macos-13'
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Configure workspace'
        run: |
          uv sync --frozen
